version: '3.3'
services:
  bitbucket:
    image: atlassian/bitbucket-server:7.0.2
    container_name: bitbucket
    labels:
      - "traefik.enable=true"
      # Web
      - "traefik.http.routers.router1.rule=Host(`$SERVER_PROXY_NAME`)" # Set this in the .env file.
      - "traefik.http.routers.router1.tls=true"
      - "traefik.http.routers.router1.tls.certresolver=route53"
      - "traefik.http.routers.router1.entrypoints=web"
      - "traefik.http.routers.router1.service=bitbucket-web"
      - "traefik.http.services.bitbucket-web.loadbalancer.server.port=7990"
      # SSH
      - "traefik.tcp.routers.router2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.router2.entrypoints=bitbucket-ssh"
      - "traefik.tcp.routers.router2.service=bitbucket-ssh"
      - "traefik.tcp.services.bitbucket-ssh.loadbalancer.server.port=7999"
    environment:
      SERVER_PROXY_NAME: ${SERVER_PROXY_NAME} # Set this in the .env file.
      SERVER_PROXY_PORT: ${SERVER_PROXY_PORT} # Set this in the .env file.
      SERVER_SCHEME: ${SERVER_SCHEME}         # Set this in the .env file.
      SERVER_SECURE: ${SERVER_SECURE}         # Set this in the .env file.
      JVM_MINIMUM_MEMORY: ${JVM_MINIMUM_MEMORY:-512m} # Set this in the .env file.
      JVM_MAXIMUM_MEMORY: ${JVM_MAXIMUM_MEMORY:-1024m} # Set this in the .env file.
    volumes:
      - data:/var/atlassian/application-data/bitbucket
    restart: unless-stopped
    stop_grace_period: 60s
    depends_on: 
     - postgres
     - traefik
volumes:
  data: {}