version: '3.3'
services:
  postgres:
    image: postgres:9.5-alpine
    container_name: postgres-bitbucket
    ports:
      - ${BITBUCKET_DB_PORT}:5432
    environment:
      POSTGRES_DB: ${BITBUCKET_DB:-bitbucket}         # Set this in the .env file.
      POSTGRES_USER: ${BITBUCKET_DB_USER:-bitbucket}  # Set this in the .env file.
      POSTGRES_PASSWORD: ${BITBUCKET_DB_PASSWORD:-""} # Set this in the .env file.
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    stop_grace_period: 60s
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
volumes:
  db: {}
