version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.bitbucket-ssh.address=:7999"
      - "--entrypoints.web.address=:443"
      - "--certificatesresolvers.route53.acme.dnschallenge=true"
      - "--certificatesresolvers.route53.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.route53.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.route53.acme.email=${AWS_ACCOUNT_EMAIL}" # Set this in the .env file.
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}         # Set this in the .env file.
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY} # Set this in the .env file.
    ports:
      - "443:443"
      - "8080:8080"
      - "7999:7999"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - letsencrypt:/letsencrypt
    restart: unless-stopped
volumes:
  letsencrypt: {}